<?php

namespace ContainerCiiTqdf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlastradiusCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Watson\Symfony\Console\BlastradiusCommand' shared autowired service.
     *
     * @return \Watson\Symfony\Console\BlastradiusCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/packages/symfony/src/Console/BlastradiusCommand.php';

        $container->privates['Watson\\Symfony\\Console\\BlastradiusCommand'] = $instance = new \Watson\Symfony\Console\BlastradiusCommand(($container->services['router'] ?? self::getRouterService($container)), \dirname(__DIR__, 4));

        $instance->setName('watson:blastradius');
        $instance->setAliases(['watson:blastradius']);
        $instance->setDescription('Report entry points whose handler files are in the diff.');

        return $instance;
    }
}
