<?php

namespace ContainerCiiTqdf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListEntrypointsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Watson\Symfony\Console\ListEntrypointsCommand' shared autowired service.
     *
     * @return \Watson\Symfony\Console\ListEntrypointsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/packages/symfony/src/Console/ListEntrypointsCommand.php';

        $container->privates['Watson\\Symfony\\Console\\ListEntrypointsCommand'] = $instance = new \Watson\Symfony\Console\ListEntrypointsCommand(($container->services['router'] ?? self::getRouterService($container)), \dirname(__DIR__, 4));

        $instance->setName('watson:list-entrypoints');
        $instance->setAliases(['watson:list-entrypoints']);
        $instance->setDescription('List every entry point Symfony registered.');

        return $instance;
    }
}
