services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Watson\Symfony\Console\ListEntrypointsCommand:
        tags:
            - { name: 'console.command' }

    Watson\Symfony\Console\BlastradiusCommand:
        tags:
            - { name: 'console.command' }
