<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCiiTqdf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCiiTqdf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCiiTqdf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCiiTqdf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCiiTqdf\App_KernelDevDebugContainer([
    'container.build_hash' => 'CiiTqdf',
    'container.build_id' => 'd381bcca',
    'container.build_time' => 1777733987,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCiiTqdf');
