<?php

namespace Container2LhKq3k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlastradiusCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Watson\Symfony\Console\BlastradiusCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Watson\\Symfony\\Console\\BlastradiusCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('watson:blastradius', ['watson:blastradius'], 'Report entry points whose handler files are in the diff.', false, #[\Closure(name: 'Watson\\Symfony\\Console\\BlastradiusCommand')] fn (): \Watson\Symfony\Console\BlastradiusCommand => ($container->privates['Watson\\Symfony\\Console\\BlastradiusCommand'] ?? $container->load('getBlastradiusCommandService')));
    }
}
