<?php

namespace Container2LhKq3k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListEntrypointsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Watson\Symfony\Console\ListEntrypointsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Watson\\Symfony\\Console\\ListEntrypointsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('watson:list-entrypoints', ['watson:list-entrypoints'], 'List every entry point Symfony registered.', false, #[\Closure(name: 'Watson\\Symfony\\Console\\ListEntrypointsCommand')] fn (): \Watson\Symfony\Console\ListEntrypointsCommand => ($container->privates['Watson\\Symfony\\Console\\ListEntrypointsCommand'] ?? $container->load('getListEntrypointsCommandService')));
    }
}
